### ISSUE TITLE
Pre-trained weights

### ISSUE THREAD

**Issue by Avishav-Engle** [dpeerlab/MaskRCNN_cell#1]
Thanks for the code implementation, would it be possible to receive (for a University Project) the .h5 file with the pre-trained weights for the cell segmentation?

**Comment by YubinXie** [comment]
Hi Avishav-Engle, thanks for reaching out. Of course. Here is the link. We trained on the following color setting: 20X, nuclei blue,  tumor red, T cells: green, yellow, pink. You can adjust ur visualization accordingly.
 https://drive.google.com/file/d/1TiwxdduQyWebCLwh6k7ixRI3mEIKyfc3/view?usp=sharing
